# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

name: R-CMD-check

jobs:
  Release:
    runs-on: macOS-latest
    
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}

    steps:
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    

      - name: Check if version has increased
        run: |
          echo "new_version="$(perl compare_versions --tag) >> $GITHUB_ENV
      
      - name: Create release
        if: ${{ env.new_version != '' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 
        with:
          tag_name: ${{ env.new_version }}
          release_name: Release ${{ env.new_version }}
          body: |
            Automatically generated release
          draft: false
          prerelease: false
          